services:
  - type: web
    name: calculadora-financiera
    runtime: docker
    plan: free
    rootDir: teenEconomia/calculadora
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: CalculadoraFinanciera
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_STACK
        value: single
      - key: LOG_LEVEL
        value: debug
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: DB_CONNECTION
        value: sqlite
